### PR TITLE
Improve table

### PR DESCRIPTION
**Pull request by rgaiacs**
Sorry for the HTML. :-(

### CODE REVIEW

**Comment by rgaiacs** [comment]
Rebased to resolve conflict. :-)

**Comment by rgaiacs** [comment]
Screenshot of the table:

screencapture-file-tmp-ssifellows-day-education-blogpost-readme-html-1489069596578

I didn't style the table since Drupal, the website content manager, most of the time remove the inline CSS. Let me know what style do you want to have (e.g. grid, even background color, ...) and I will do our best.

**Comment by lbillingham** [comment]
@rgaiacs As there is a mix of content length in different cells, I think it might be good have more differentiation between row (and, to a lesser extent columns). Maybe zebra-striping the backgrounds or putting in cell borders.

I'm a little confused by the 'Domain Specific' and 'Offers' columns. Could it be worth including a concrete examples

e.g.
 'Domain Specific' : {No; at subject-group level e.g. all students doing fluid flow modelling; at sub-group level e.g. everyone modelling multi-phase flow }?

**Comment by rgaiacs** [comment]
> As there is a mix of content length in different cells, I think it might be good have more differentiation between row (and, to a lesser extent columns). Maybe zebra-striping the backgrounds or putting in cell borders.

I can do it on Drupal. I will  not do it on GitHub to avoid add CSS into the Markdown.

> I'm a little confused by the 'Domain Specific' and 'Offers' columns. Could it be worth including a concrete examples

@kks32 Could you provide me with a better column header or some examples.

**Pull request merged**
